### PR TITLE
VL: Disable bilinear interpolation in VI

### PR DESCRIPTION
**Pull request by thekovic**
Disables bilinear interpolation when VI scales the line width to 640. Produces a sharper, more DOS-like appearance. We can do this even on NTSC consoles at 16-bit depth thanks to the fact you pad the resolution to 352x216 (I assume to account for overscan?)

### CODE REVIEW

**Comment by 9nova** [comment]
This looks noticeably worse for me in some areas like the text on the menu

Screenshot 2023-10-26 13-01-46

**Comment by Wolf3s** [comment]
> This looks noticeably worse for me in some areas like the text on the menu

It´s most likely i´m playing at 90s or something like

**Comment by thekovic** [comment]
@9nova I see what you mean - the word "Control" (mainly the C) and the lopsided B in "Back to Game/Back to Demo".

The reason behind that is line doubling. If you push a frame of <240 lines, the N64 will double some of them to get to 240 lines, if the interpolation is disabled. When it's enabled, the new lines get blended in rather smoothly. It's a shame because otherwise, I rather enjoy the sharp look. If a 240 line image could be pushed, one could achieve a completely perfectly scaled image that would be sharp but that would require a different overscan solution.

image

**Comment by 9nova** [comment]
Hard to imagine there's any good solution here because the original game expects 320x200 with non-square pixels.

- using 320x240 will result in sharp pixels but the image will be squashed
- correcting to 384x240 to preserve the aspect ratio will cause horizontal doubling and require resampling again

Can't think of anything else short of redrawing all the assets to be in a format expecting square pixels.

**Comment by thekovic** [comment]
I was disappointed to realize the N64 can't do non-square pixels and instead fills the image to 240 lines. I believe PS1 doesn't care; doesn't do this.

Well, you're right - I can't think of a solution that would preserve the presentation and produce a sharp image at the same time either. I think I will close the PR.

**Pull request closed without merging**
